---
functional:
  - Возможность авторизации с помощью аккаунта на Github 
  - Возможность регистрации и авторизации с помощью email и пароля
  - Возможность восстановить пароль с помощью email
  - Победителем должен являться тот, кто верно решил задачу и затратил на это меньше времени 
  - Возможность выбора языка программирования в терминале игры
  - Возможность настраивать параметры игры; сложность, выбор оппонента, лимит времени, тип задания 
  - Возможность создать поединок с другим пользователем/другом/ботом
  - Возможность проматривать статистику по поединкам, чемпионатам и игрокам 
  - Возможность участия пользователей в турнире и турнирной сетке
  - Возможность переподключения участника к игре 
  - Возможность отправлять приглашение на игру другим пользователям 
  - Возможность просмотра истории игры
  - Возможность просмотра повтора игры
  - Возможность находиться только в одной игре одновременно
  - Реалиазована возможность общения в чате игры для зарегестрированных пользователей
  - Реализована возможность подключения к игре другим пользователям в качестве зрителей
  - Реализация функции сдаться, сброса кода, проверки решения в терминале 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Реализация мультиязычности
implicit:
  - Участник не может писать и изменять код в терминале соперника
  - Зрители не могут писать код и вносить изменения в терминалах участников
  - Возможность оставить обратную связь об ошибках на сайте игры
  - Участники не могут вносить изменения в предустановленную задачу баттла
